[[language]]
name = "nix"
scope = "source.nix"
injection-regex = "nix"
file-types = ["nix"]
roots = ["flake.nix", "shell.nix", "default.nix", ".nixos-config"]
auto-format = true
language-servers = [ "nil" ]

[language-server.nil]
command = "nil"

[[language]]
name = "bash"
scope = "source.bash"
injection-regex = "(ba|z)?sh"
file-types = ["sh", "bash", "zsh"]
shebangs = ["sh", "bash", "zsh"]
roots = [".bashrc", ".bash_profile", ".zshrc"]
language-servers = [ "bash-language-server" ]

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[[language]]
name = "yaml"
scope = "source.yaml"
injection-regex = "yaml"
file-types = ["yml", "yaml"]
language-servers = [ "yaml-language-server" ]

[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
language-servers = [ "rust-analyzer" ]

[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "pyc", "pyd", "pyw"]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "Poetry.lock", "poetry.lock"]
language-servers = [ "ruff-lsp" ]

[language-server.ruff-lsp]
command = "ruff-lsp"
